RUN:
  "20200306_0095"
SAMPLETABLE:
  "/users/home/cat3/projects/mime-16s/data/miseq/20200306_0095/samples.csv"
ORIENTATION:
  - "R1"
  - "R2"
PRIMERS:
  - 515F-806R: "^ACGGGGYGCAGCAGGCGCGA...AGCGCGGACGACGYGGGGCA", "^AGCGCGGACGACGYGGGGCA...ACGGGGYGCAGCAGGCGCGA"
  - 344F: "^ACGGGGYGCAGCAGGCGCGA...AGCGCGGACGACGYGGGGCA"
  - 915R: "^GTGCTCCCCCGCCAATTCCT...TCCTTAACCGCCCCCTCGTG"
  - 349F: "^TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGYGCASCAGKCGMGAAW"
  - 519R: "^GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGTTACCGCGGCKGCTG"
