RUN:
  "20200306_0095"
SAMPLETABLE:
  "/users/home/cat3/projects/mime-16s/data/miseq/20200306_0095/samples.csv"
ORIENTATION:
  - "R1"
  - "R2"
EMP: # 515F-806R
  - "^GTGCCAGCMGCCGCGGTAA...ATTAGAWACCCBDGTAGTCC"
  - "^GGACTACHVGGGTWTCTAAT...TTACCGCGGCKGCTGGCAC"
ARK: # 344F-915R
# GTGCAGCAGGCGCGA
  - "^ACGGGGYGCAGCAGGCGCGA...AGCGCGGACGACGYGGGGCA"
  - "^GTGCTCCCCCGCCAATTCCT...TCCTTAACCGCCCCCTCGTG"
ARK2: #349F-519R
  - "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGYGCASCAGKCGMGAAW"
  # CA.CAG.CG.GAA. in   4431 /5202
  - "GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGTTACCGCGGCKGCTG"
  # TTACCGCGGC.GCTG in 4337/5202
