RUN:
  "20190915_0082"
SAMPLETABLE:
  "/users/home/cat3/projects/mime-16s/data/miseq/20190915_0082/samples.csv"
ORIENTATION:
  - "R1"
  - "R2"
EMP: # 515F-806R
  - "^ACGGGGYGCAGCAGGCGCGA...AGCGCGGACGACGYGGGGCA"
  - "^AGCGCGGACGACGYGGGGCA...ACGGGGYGCAGCAGGCGCGA"
ARK: # 344F-915R
  - "^ACGGGGYGCAGCAGGCGCGA...AGCGCGGACGACGYGGGGCA"
  - "^GTGCTCCCCCGCCAATTCCT...TCCTTAACCGCCCCCTCGTG"
ARK2: #349F-519R
  - "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGYGCASCAGKCGMGAAW"
  - "GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGTTACCGCGGCKGCTG"
