RUN:
  "20190508_0074"
SAMPLETABLE:
  "/users/home/cat3/projects/mime-16s/data/miseq/20190508_0074/samples.csv"
ORIENTATION:
  - "R1"
  - "R2"
PRIMERS: # 515F-806R
  - "-a ^GTGCCAGCMGCCGCGGTAA...ATTAGAWACCCBDGTAGTCC"
  - "-A ^GGACTACHVGGGTWTCTAAT...TTACCGCGGCKGCTGGCAC"
MAXLEN:
  300
MINLEN:
  220
FWDTRUNCLEN:
  250
REVTRUNCLEN:
  200
