RUN:
  "20200515_0106"
SAMPLETABLE:
  "/users/home/cat3/projects/mime-16s/data/miseq/20200515_0106/samples.csv"
ORIENTATION:
  - "R1"
  - "R2"
PRIMERS:
  - "-b TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGYGCASCAGKCGMGAAW"
  - "-B GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGTTACCGCGGCKGCTG"
MAXLEN:
  170
MINLEN:
  100
FWDTRUNCLEN:
  100
REVTRUNCLEN:
  100
