RUN:
  "20200506_0104"
SAMPLETABLE:
  "/users/home/cat3/projects/mime-16s/data/miseq/20200506_0104/samples.csv"
ORIENTATION:
  - "R1"
  - "R2"
PRIMERS:
  - "-b TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGYGCASCAGKCGMGAAW"
  - "-B GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGTTACCGCGGCKGCTG"
MAXLEN:
  170
MINLEN:
  100
FWDTRUNCLEN:
  100
REVTRUNCLEN:
  100
