channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - fastqc==0.11.9
  - trimmomatic==0.36
  - pigz==2.3.4
  - snakemake-wrapper-utils==0.1.3
  - cutadapt==2.10
  - bioconductor-dada2==1.16
  - python=3.8.3
  - snakemake=5.32.0
